
FROM php:8.2-fpm

# Set working directory
WORKDIR /var/www/html

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy project ke dalam container
COPY ./src /var/www/html

# Copy directory project permission ke container
COPY --chown=www-data:www-data . /var/www/html
RUN chown -R www-data:www-data /var/www/html

# Install dependency
RUN composer install

# Expose port 9000
EXPOSE 9000

# Ganti user ke www-data
USER www-data
