version: '3.7'

networks:
  laravel-chat-app-realtime:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-laravel-docker-chat-app-realtime
    ports:
      - "8083:80"
    volumes:
      - ./src/:/var/www/html
      - ./local/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./local/nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ./local/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - laravel-chat-app-realtime

  php:
    build:
      context: .
      dockerfile: Dockerfile-local
    container_name: php-laravel-chat-app-realtime
    volumes:
      - ./src/:/var/www/html
    ports:
      - "9003:9000"
    networks:
      - laravel-chat-app-realtime
